web/app/random_number_app/urls.py
from django.urls import path
from .views import HomeView, NumberView


app_name = 'random_number_app'

urlpatterns = [
   path('', HomeView.as_view(), name='home'),
   path('number/', NumberView.as_view(), name='get_number'),
]

web/app/users/urls.py
from django.contrib.auth.views import LogoutView, LoginView
from django.urls import path


app_name = 'users'

urlpatterns = [
   path('logout/', LogoutView.as_view(), name='logout'),
   path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),
]

web/web/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('social_django.urls', namespace='social')),
    path('', include('app.random_number_app.urls', namespace='random_number_app')),
    path('', include('app.users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

web/app/random_number_app/models.py
from django.db import models

# Create your models here.

web/app/users/models.py
from django.db import models

# Create your models here.

web/app/random_number_app/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.views.generic import TemplateView, View
from .redis_client import redis_client


class HomeView(LoginRequiredMixin, TemplateView):
    template_name = 'random_number_app/home.html'


class NumberView(View):
    def get(self, request, *args, **kwargs):
        number = redis_client.get('random_number')

        if number is None:
            redis_client.set('random_number', 1)

        return JsonResponse({'number': number})

web/app/users/views.py
from django.shortcuts import render

# Create your views here.

web/app/random_number_app/templates/random_number_app/home.html
{% extends 'base.html' %}
{% block title %}Random!{% endblock %}

{% block content %}
    <div class="welcome_section">
        <h1>Welcome, {{ user.username }}!</h1>
    </div>

    <div class="logout_button">
        <form action="{% url 'users:logout' %}" method="post">
            {% csrf_token %}
            <button type="submit">Logout</button>
        </form>
    </div>

    <div class="random_number_section">
        <h1>Random Number: <span id="random-number" class="random-number"></span></h1>
    </div>
{% endblock %}

web/app/users/templates/users/login.html
{% extends 'base.html' %}
{% block title %}Login{% endblock %}
{% block login %}
    <div class="login_section">
        <h1>Login</h1>
        <a href="{% url 'social:begin' 'github' %}">Login with GitHub</a>
    </div>
{% endblock %}

web/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>

    {% load static %}
    <link rel="stylesheet" href="{% static 'random_number_app/css/styles.css' %}">
</head>
<body>
    {% block login %}{% endblock %}
    {% block content %}{% endblock %}
    <script src="{% static 'random_number_app/js/random_number.js' %}"></script>
</body>
</html>